[project]
name = "biotrainer-vis"
version = "0.1.0"
description = "Standardized visualization library for biological datasets based on biotrainer-core dataclasses"
readme = "README.md"
requires-python = ">=3.11, <3.14"
dependencies = [
    "altair>=6.0.0",
    "vl-convert-python>=1.9.0.post1",
    "biotrainer-core>=0.1.0"
]

[tool.uv.sources]
biotrainer-core = { workspace = true }